spring:
  application:
    name: comment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # Feign 熔断降级
    openfeign:
      circuitbreaker:
        enabled: true
  # MongoDB 配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/school
      database: weave
      auto-index-creation: true

server:
  port: 4400

# 日志配置
logging:
  level:
    root: info
    org.example: debug
