spring:
  whitelist:
    paths:
      - /api/auth/login
      - /api/auth/register/**
      - /api/club/**
      - /api/post/**
      - /api/posts/files/**
      - /api/user/info/**
      - /api/users/avatar/**
      - /api/search/**