spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 全局跨域配置
            allowedOrigins: "*" # 允许跨域请求的源
            allowedMethods: "*" # 允许跨域请求的方法
            allowedHeaders: "*" # 允许跨域请求的头部

      routes: # 路由配置
        - id: service-auth
          uri: lb://service-auth # 路由的目标地址
          predicates: # 断言，判断请求是否符合要求
            - Path=/api/auth/** # 请求路径匹配

        - id: service-comment
          uri: lb://service-comment
          predicates:
            - Path=/api/comment/**

        - id: service-post
          uri: lb://service-post
          predicates:
            - Path=/api/post/**