spring:
  whitelist:
    paths:
      # CLUB
      - GET:/api/club/**
      # POST
      - GET:/api/post/**
      # USER
      - GET:/api/user/info
      - GET:/api/user/info/{id}
      - GET:/api/users/avatar/**
      # SEARCH
      - GET:/api/search/**
      # AUTH
      - POST:/api/auth/login
      - POST:/api/auth/register/**
