spring:
  whitelist:
    paths:
      - /api/auth/login
      - /api/auth/register
      - /api/auth/logout
      - /api/resources
      - /api/clubs/**
      - /api/resources/presign
      - /api/posts