# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_stubs import rag_service_pb2 as rag__service__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RAGServiceStub:
    """RAG 查询服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
                '/rag.RAGService/Ask',
                request_serializer=rag__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=rag__service__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.AskStream = channel.unary_stream(
                '/rag.RAGService/AskStream',
                request_serializer=rag__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=rag__service__pb2.StreamChunk.FromString,
                _registered_method=True)


class RAGServiceServicer:
    """RAG 查询服务
    """

    def Ask(self, request, context):
        """用户提问，返回纯文本回答
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskStream(self, request, context):
        """用户提问，流式返回回答（server-streaming）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=rag__service__pb2.QueryRequest.FromString,
                    response_serializer=rag__service__pb2.QueryResponse.SerializeToString,
            ),
            'AskStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AskStream,
                    request_deserializer=rag__service__pb2.QueryRequest.FromString,
                    response_serializer=rag__service__pb2.StreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.RAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.RAGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGService:
    """RAG 查询服务
    """

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RAGService/Ask',
            rag__service__pb2.QueryRequest.SerializeToString,
            rag__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.RAGService/AskStream',
            rag__service__pb2.QueryRequest.SerializeToString,
            rag__service__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
