# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'rag_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rag_service.proto\x12\x03rag\" \n\x0cQueryRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1f\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"\x1c\n\x0bStreamChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\t2n\n\nRAGService\x12,\n\x03\x41sk\x12\x11.rag.QueryRequest\x1a\x12.rag.QueryResponse\x12\x32\n\tAskStream\x12\x11.rag.QueryRequest\x1a\x10.rag.StreamChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=26
  _globals['_QUERYREQUEST']._serialized_end=58
  _globals['_QUERYRESPONSE']._serialized_start=60
  _globals['_QUERYRESPONSE']._serialized_end=91
  _globals['_STREAMCHUNK']._serialized_start=93
  _globals['_STREAMCHUNK']._serialized_end=121
  _globals['_RAGSERVICE']._serialized_start=123
  _globals['_RAGSERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
