spring:
  application:
    name: service-chat
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  tracing:
    sampling:
      probability: 1.0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation-design-chat?serverTimezone=UTC
    username: root
    password: ALIEZ2436946
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

server:
  port: 8083

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
